# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{forkcms_deploy}
  s.version = "1.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tijs Verkoyen", "Jan De Poorter"]
  s.date = %q{2011-10-07}
  s.description = %q{Deployment for Fork with Capistrano}
  s.email = %q{info@sumocoders.be}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION",
    "forkcms_deploy.gemspec",
    "lib/forkcms_deploy.rb",
    "lib/forkcms_deploy/defaults.rb",
    "lib/forkcms_deploy/forkcms.rb",
    "lib/forkcms_deploy/overwrites.rb"
  ]
  s.homepage = %q{http://github.com/tijsverkoyen/forkcms_deploy}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Deployment for Fork with Capistrano}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, [">= 2.0.0"])
    else
      s.add_dependency(%q<capistrano>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<capistrano>, [">= 2.0.0"])
  end
end

